name: Publish Docker image with Docker Compose

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub using Docker Compose
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push images with Docker Compose
      - name: Build and Push Images
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for better performance
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
