name: Build, Push, and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: registerdat250.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    # Step 3: Build and push Docker images
    - name: Build and Push API Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: registerdat250.azurecr.io/api:latest

    - name: Build and Push Messaging Image
      uses: docker/build-push-action@v6
      with:
        context: https://github.com/Thorbjorn2021/project-Messaging.git
        push: true
        tags: registerdat250.azurecr.io/messaging:latest

